### ISSUE TITLE
Dynamic inventory only picks up SSH target port and only if no other ports have been set  in the service.

### ISSUE THREAD

**Issue by budgester** [kubevirt/kubevirt.core#167]
##### SUMMARY
I am running against an Openshift cluster trying to connect to an assortment of VM's Windows and Linux, 

The virtual inventory will only pick up a service if it is the only defined service and it is ssh.

When trying to use ansible to connect to a windows machine we should allow access to winrm on port 5985, 5986 if they are defined in an attached service

example service

```
apiVersion: v1
kind: Service
metadata:
  name: windows-server-a-ansible
  namespace: demo
spec:
  selector:
    kubevirt.io/domain: windows-server-a
  ports:
    - name: winrm
      protocol: TCP
      port: 5985
      targetPort: 5985
```

Currently the code at

https://github.com/kubevirt/kubevirt.core/blob/main/plugins/inventory/kubevirt.py#L597-L604

```
            # Continue if ports are not defined, there are more than one port mapping
            # or the target port is not port 22/ssh
            if (
                (ports := spec.get("ports")) is None
                or len(ports) != 1
                or ports[0].get("targetPort") != 22
            ):
                continue
```

This is pretty crude but but something like below would setup the inventory to point via a Nodeport that is forwarded to a winrm listener.

```
            access_ports = [22,5985,5986]
            if (
                (ports := spec.get("ports")) is None
                or len(ports) != 1
                or ports[0].get("targetPort") in access_ports
            ):
                continue
```

We could attach a separate service to the VM just for access from ansible if there are other services being forwarded via the node port, but will need to add this as a note in the documentation.

It would also be useful to add to the documentation to set the connection type to winrm we need to add an annotation with a value prefix of windows e.g. `vm.kubevirt.io/os: windows-***` to the virtual machine.
