### ISSUE TITLE
Modify existing VM

### ISSUE THREAD

**Issue by badnetmask** [kubevirt/kubevirt.core#30]
##### SUMMARY
The current `kubevirt_vm` module can only be used to create/remove/start/stop a VM, but it's unable to modify an existing VM. Here's an example use-case:
- Create the VM in stopped state with a bridged network interface.
- Grab the MAC address of the bridged interface.
- Find an available IP address in IPAM and make a reservation.
- Modify the VM to define the static IP address via cloud-init.
- Start the VM.

##### ISSUE TYPE
 - Feature Idea

**Comment by 0xFelix** [comment]
This sounds like a limitation of cloud-init, not an issue of `kubevirt_vm` or `KubeVirt`.

Did the module succeed in modifying the VM? Can you attach the YAML of the VM before and after the modification?

**Comment by 0xFelix** [comment]
Also see the docs of `cloud-init`'s stages: https://cloudinit.readthedocs.io/en/latest/explanation/boot.html#local

> If this is an instance’s first boot, then the selected network configuration is rendered.

Network configurations are only applied on the first boot of a VM, not on subsequent boots. So this is a `cloud-init` limitation.

**Comment by badnetmask** [comment]
The issue is really not with cloud-init, but with additional parameters we want to inject into the VM definition, which _can include_ cloud-init. I'll try to provide brief examples to not pile up with too much data here.
```
- name: Create the basic VM
  kubevirt.core.kubevirt_vm:
    register: vm_info
    state: present
    running: false
    (...)
    spec:
          (...)
          devices:
            disks:
              - bootOrder: 1
                disk:
                  bus: virtio
                name: "myvm-root"
            interfaces:
              - name: eth0
                masquerade: {}
              - name: eth1
                bridge: {}
        networks:
          - name: eth0
            pod: {}
          - name: eth1
            multus:
              networkName: bridgedvlan
        volumes:
          - dataVolume:
              name: "myvm-datavolume"
            name: "myvm-root"
```

Once the VM is created, I can grab the eth1 MAC address using `vm_info.result.spec.template.spec.domain.devices.interfaces[1].macAddress`, and with that I can create the appropriate DNS entries and DHCP reservation. After that, I want to tell the VM that it has a static IP, so it doesn't try to do DHCP.
```
- name: Pass the network info to the VM and start it
  register: vm_info
  kubevirt.core.kubevirt_vm:
    state: present
    running: true
    (...)
    spec:
      domain:
        disks:
          - bootOrder: 1
             disk:
               bus: virtio
             name: "myvm-root"
          - disk:
              bus: virtio
            name: cloudinitdisk
      volumes:
        - dataVolume:
            name: "myvm-datavolume"
          name: "myvm-root"
        - cloudInitNoCloud:
            network:
              version: 2
              ethernets:
                eth1:
                  dhcp4: no
                  addresses:
                    - "{{ nic_ip_address }}/{{ nic_cidr_prefix }}"
                  nameservers:
                    - "{{ dns_nameserver_1 }}"
                    - "{{ dns_nameserver_2 }}"
                  routes:
                    - to: 192.168.0.0/24
                      via: "{{ vmNetworkGateway }}"
            userData: |-
              #cloud-config
              user: "{{ vmSSHUser }}"
              ssh_authorized_keys:
                - "{{ vmSSHKey }}"
              fqdn: {{ inventory_hostname }}
            name: cloudinitdisk
```

The problem is: once I define the VM for the first time, the second run does not make any changes to the VM definition. All it does is just start the VM.

I could probably patch the VM definition using `kubernetes.core.k8s_json_patch`, but I would prefer to have it simpler, by just passing the new values to the `kubevirt.core.kubevirt_vm` module.

It appears like [the old `kubevirt_vm` module was capable](https://docs.ansible.com/ansible/2.9/modules/kubevirt_vm_module.html#parameter-merge_type) of doing what I am asking, but this was never ported to the new module when it was moved out of the community repo.
