### ISSUE TITLE
[kubevirt_vm] Impossible to use variables for cpu.cores and cpu.threads

### ISSUE THREAD

**Issue by newkit** [kubevirt/kubevirt.core#87]
Downstream bug report:[https://issues.redhat.com/browse/ACA-1390](https://issues.redhat.com/browse/ACA-1390)

It is not possible to create a VM with Ansible kubvirt_vm module and provide the amount of CPU cores or threads through another variable. The reason is, that the kubevirt_vm module expects those values to be integers, but due to constraints in Ansible the values always end up to be integers.

**Examples (only relevent parts are shown)**

1. Working example

```
- name: Provision KubeVirt Virtual Machine
  kubevirt.core.kubevirt_vm:
  ...
  spec:
    domain:
     ...
        cpu:
          cores: 2
          threads: 2

```
 

2. This is not working

```
- name: Set fact for kubevirt_vm_cpu_cores
  ansible.builtin.set_fact:
     kubevirt_vm_cpu_cores: 2

- name: Provision KubeVirt Virtual Machine
  kubevirt.core.kubevirt_vm:
  ...
  spec:
    domain:
     ...
        cpu:
          cores: "{{ kubevirt_vm_cpu_cores | int }}"
          threads: 2
```

 

Debug output shows that

```
TASK [sap_vm_provision : Set fact for kubevirt_vm_cpu_cores] *********************************************************************************************************************************
task path: /home/nils/data/git/community.sap_infrastructure/roles/sap_vm_provision/tasks/platform_ansible/redhat_ocp_virt/execute_provision.yml:190
ok: [localhost] => {
    "ansible_facts": {
        "kubevirt_vm_cpu_cores": 2
    },
    "changed": false
}
 
```
 

While the variable set in Ansible is clearly an integer, it does not get properly "casted" when inserting it within the yaml section:

```
           "spec": {
                "domain": {
                    "cpu": {
                        "cores": "2",
...
                        "threads": 2
                    },
```

The error message is as follows:

```
    "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"admission webhook \\\\\"mutatevirtualmachines.kubemacpool.io\\\\\" denied the request: json: cannot unmarshal string into Go struct field VirtualMachineInstanceTemplateSpec.spec.template.spec of type uint32\",\"code\":400}\\n'",
    "reason": "Bad Request" 
```
 

This is a blocker in order to use kubevirt_vm for the community.sap_infrastructure.sap_vm_provision role.

**Versions**

```
ansible --version
ansible [core 2.16.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nils/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/nils/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

kubevirt-core-1.2.3
```

**Comment by fabiand** [comment]
Why do you need to set cores and threads?

**Comment by 0xFelix** [comment]
From what I can tell, this works without any special settings:

```
---
- hosts: localhost
  tasks:
    - name: Set cores
      ansible.builtin.set_fact:
        kubevirt_vm_cpu_cores: 2
    - name: Create VM
      kubevirt.core.kubevirt_vm:
        state: present
        name: testvm
        namespace: default
        spec:
          domain:
            cpu:
              sockets: 1
              cores: "{{ kubevirt_vm_cpu_cores }}"
              threads: 1
            devices: {}
```

Note that it does not work if the fact is defined like so `kubevirt_vm_cpu_cores: "2"`, or when using the `int` filter like so `cores: "{{ kubevirt_vm_cpu_cores | int }}"`.

Afterall, I think this is an issue with Ansible, not with the collection.

**Comment by newkit** [comment]
What if you define it in a nested variable structure in the vars section?  E.g. 
```
---
- hosts: localhost
  vars:
    kubevirt_vm:
      cpu_cores: 2
  tasks:
    - name: Create VM
      kubevirt.core.kubevirt_vm:
        state: present
        name: testvm
        namespace: default
        spec:
          domain:
            cpu:
              sockets: 1
              cores: "{{ kubevirt_vm.cpu_cores }}"
              threads: 1
            devices: {}

```
And just to be sure, you don't set `ANSIBLE_JINJA2_NATIVE=true`, correct?

**Comment by 0xFelix** [comment]
This also works:

```
---
- hosts: localhost
  vars:
    kubevirt_vm_cpu_cores: 2
  tasks:
    - name: Create VM
      kubevirt.core.kubevirt_vm:
        state: present
        name: testvm
        namespace: default
        spec:
          domain:
            cpu:
              sockets: 1
              cores: "{{ kubevirt_vm_cpu_cores }}"
              threads: 1
            devices: {}
```

This does **NOT** work:

```
---
- hosts: localhost
  vars:
    kubevirt_vm:
      cpu_cores: 2
  tasks:
    - name: Create VM
      kubevirt.core.kubevirt_vm:
        state: present
        name: testvm
        namespace: default
        spec:
          domain:
            cpu:
              sockets: 1
              cores: "{{ kubevirt_vm.cpu_cores }}"
              threads: 1
            devices: {}
```

To me it still looks like an issue within Ansible. There is not much we can do about it in the collection.
